name: Waka Stats Updater

on:
  workflow_run:
    workflows: ["ReadMe Stats Updater"]
    branches: [master]
    types: 
      - completed

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
